# Generated by Django 3.1.5 on 2021-01-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210118_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='close_treasure',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
