# Generated by Django 3.1.5 on 2021-01-19 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('seeker', models.CharField(blank=True, max_length=50, null=True)),
                ('timeSought', models.CharField(blank=True, max_length=30, null=True)),
                ('hider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
