# Generated by Django 3.1.5 on 2021-01-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0002_auto_20210119_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='seeker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
